SELECT U.USERID, U.FIRST_NAME, U.LAST_NAME -
FROM USERS U -
WHERE U.USERID IN -
((SELECT UG.USERID FROM USERGRP UG -
WHERE UG.GRPID IN (SELECT GRPID FROM USERGRP -
GROUP BY GRPID -
HAVING COUNT(*) > 9)) -
MINUS-
(SELECT P.SENDER_ID FROM POST P - 
WHERE P.DATETIME BETWEEN (SELECT TO_CHAR(SYSDATE-7,'DD-MON-YY') from DUAL) AND -
( SELECT TO_CHAR(SYSDATE,'DD-MON-YY') from DUAL))); 

