SELECT U1.USERID AS USER1, U1.FIRST_NAME, U1.LAST_NAME, U1.EMAIL,-
U2.USERID AS USER2, U2.FIRST_NAME, U2.LAST_NAME, U2.EMAIL -
FROM USERS U1, USERS U2, USERGRP UG1 -
WHERE U1.COUNTRY = 'USA' AND U2.COUNTRY = 'USA' AND U1.USERID = UG1.USERID -
AND U1.USERID < U2.USERID -
AND UG1.GRPID IN (SELECT DISTINCT UG.GRPID -
FROM USERGRP UG -
WHERE UG.USERID IN (SELECT U.USERID FROM USERS U -
WHERE U2.USERID = U.USERID))-
ORDER BY U1.USERID;
