SELECT P.POST_CONTENT -
FROM USERS U, POST P -
WHERE U.USERID = P.SENDER_ID AND U.FIRST_NAME = 'Jackie' AND U.LAST_NAME = 'Chan' -
AND P.ATTACH_RES IS NULL AND -
P.DATETIME BETWEEN TO_DATE('01/01/2014','MM/DD/YYYY') AND TO_DATE('01/31/2014','MM/DD/YYYY');