SELECT U.EMAIL -
FROM USERS U -
WHERE U.USERID IN ( -
SELECT UC.USERID -
FROM USERS U, USER_CONN UC -
WHERE U.USERID = UC.CONNECTID - 
AND U.FIRST_NAME = 'Jackie' AND U.LAST_NAME = 'Chan' -
INTERSECT -
SELECT UC.USERID -
FROM USERS U, USER_CONN UC -
WHERE U.USERID = UC.CONNECTID - 
AND U.FIRST_NAME = 'Lady' AND U.LAST_NAME = 'Gaga');